### ISSUE TITLE
自転車の空気入れに関する情報があると良いのではないか

### ISSUE THREAD

**Issue by oageo** [ZDK-UTsukuba/hello2024-frontend#54]
直接話した: @eniehack 

平砂カスミ付近の空気入れが撤去され、代替となる自由に使える自転車の空気入れの場所の需要があるのではないかと予想されるため

**Comment by oageo** [comment]
記事を新しく追加することで対処することになった

**Comment by Crow314** [comment]
コンテンツについてはこのリポジトリの所管するところではない(なんなら本来IPC所管ではない)という認識ですが、このIssueはCloseします？ (なんならDeleteでも良いが)
